name: Setup environment
description: |
  This action prepares the environment for gradle execution by:
  - Setting the Java version to 17
  - Decodes and creates the Google services json file
  - Setting up Gradle and restoring its cache
inputs:
  google_services_json:
    description: Google services json file contents in base 64
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Java version to 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Decode and create Google services json file
      shell: bash
      run: |
        echo "${{ inputs.google_services_json }}" > "./encoded"
        base64 --decode < "./encoded" > "./app/google-services.json"
        cat "./app/google-services.json"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
