# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  android: "2.1.2"

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  test-report:
    executor:
      name: android/android-machine
      resource-class: xlarge
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew createTestCoverageReport
          system-image: system-images;android-30;google_apis;x86
      - android/save-gradle-cache

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-report:
    jobs:
      - test-report
