# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  android: circleci/android@2.3.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  test-report:
    machine:
      image: android:202102-01
      # To optimize build times, we recommend "large" and above for Android-related jobs
      resource_class: large
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version
      - android/change-java-version:
          java-version: 17
      - android/restore-gradle-cache
      - android/start-emulator-and-run-tests:
          system-image: system-images;android-29;default;x86
          test-command: ./gradlew createTestCoverageReport
      - android/save-gradle-cache

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-report:
    jobs:
      - test-report
