# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy a new version to the Google Play"
  lane :upload_alpha do
    require 'open-uri'

    json_key = File.new("google_play_key.json")

    open('google_play_key.json', 'wb') do |file|
        file << open(ENV["BITRISEIO_GOOGLE_PLAY_KEY_JSON_URL"]).read
    end


    # upload_to_play_store(
    #     track: "alpha",
    #     json_key: json_key,
    # )
  end
end
