#!/bin/bash
set -x

adb start-server
nohup emulator -avd Emulator -no-audio -netdelay none -no-snapshot -wipe-data -gpu auto -no-window -no-boot-anim -camera-back none -camera-front none &
adb wait-for-device
