#!/bin/bash
set -x

file="./version"

while IFS='=' read -r key value
do
  key=$(echo "$key" | tr '.' '_')
  eval "${key}"=\${value}
done < "$file"

next_patch_version=$((version_patch + 1))

cat <<END > "$file"
version.major=$version_major
version.minor=$version_minor
version.patch=$next_patch_version
version.build=0
END

cat "$file"

echo "$version_major.$version_minor.$next_patch_version.0" > version.txt
