#!/bin/bash

file="./version"

while IFS='=' read -r key value
do
  key=$(echo "$key" | tr '.' '_')
  eval "${key}"=\${value}
done < "$file"

next_major_version=$((version_major + 1))

cat <<END > "$file"
version.major=$next_major_version
version.minor=0
version.patch=0
version.build=0
END

cat "$file"

echo "$next_major_version.0.0.0" > version.txt