#!/bin/bash
set -x

version=$(<"version.txt")

gh release create "v$version" \
  --title "NetShare Explorer v$version" \
  app/build/outputs/apk/release/app-release.apk \
  app/build/outputs/bundle/release/app-release.aab
