#!/bin/bash
set -x

git config --global user.name "TeamCity"
git config --global user.email "msd117c@gmail.com"

version=$(<"version.txt")

git add version
git commit -m "Increment version to $version"
git tag -a "v$version" -m "Version $version"
