name: Android CI
on:
  pull_request_target:
    type:
      - opened
    branches:
      - main
jobs:
  Test-coverage-report:
    runs-on: macos-latest
    steps:
      - name: Start emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Run debug test cases with Gradle
        run: ./gradlew createTestCoverageReport
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/**/*.xml
          token: ${{ secrets.TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
