name: Test jobs
run-name: Test jobs for ${{ github.ref_name }}
on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  unit-test:
    steps:
      - name: Check if Kotlin unit test cases related files changed
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            unit_tests:
              - 'src/main/**.kt'
              - 'src/test/**.kt'
              - '**.kts'

      - name: Trigger unit test cases
        if: steps.changes.outputs.unit_tests == 'true'
        uses: ./.github/workflows/unit_test.workflow.yml
