name: Test jobs
run-name: Test jobs for ${{ github.ref_name }}
on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  unit-test:
    uses: ./.github/workflows/unit_test.workflow.yml
