name: Unit tests
run-name: Unit tests on {{ github.ref_name }}
on:
  workflow_call:
    paths:
      - '**.kt'
      - '**.kts'
  workflow_dispatch:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Java version to 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run unit tests
        run: ./gradlew debugUnitTest --continue --scan

      - name: Publish Unit Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
